using Microsoft.VisualStudio.TestTools.UnitTesting;

using Renci.SshNet.Security.Cryptography.Ciphers;
using Renci.SshNet.Tests.Common;

namespace Renci.SshNet.Tests.Classes.Security.Cryptography.Ciphers
{
    /// <summary>
    /// Implements DES cipher algorithm.
    /// </summary>
    [TestClass]
    public class DesCipherTest : TestBase
    {
        // All tests below this line were generated by the script in DesCipherTest.Gen.cs.txt
        [TestMethod]
        public void DES_CBC_Length8_NoPad()
        {
            var input = new byte[]
            {
                0x03, 0xe1, 0xe1, 0xaa, 0xa5, 0xbc, 0xa1, 0x9f,
            };
            var key = new byte[]
            {
                0xba, 0x8c, 0x42, 0x05, 0x8b, 0x4a, 0xbf, 0x28,
            };
            var iv = new byte[]
            {
                0x96, 0x39, 0xec, 0x0d, 0xfc, 0x2d, 0xb2, 0x7c,
            };

            // echo -n -e '\x03\xe1\xe1\xaa\xa5\xbc\xa1\x9f' | openssl enc -e -des-cbc -K BA8C42058B4ABF28 -iv 9639EC0DFC2DB27C -provider legacy -nopad | hd
            var expected = new byte[]
            {
                0x46, 0x02, 0xdd, 0x47, 0xe2, 0xe4, 0x1c, 0x7e,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: false).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: false).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CBC_Length8_Pad()
        {
            var input = new byte[]
            {
                0xe9, 0x74, 0x8e, 0x5f, 0xb9, 0xf3, 0x99, 0xce,
            };
            var key = new byte[]
            {
                0xe1, 0x1a, 0x5c, 0x51, 0xa3, 0x1d, 0xd7, 0x1b,
            };
            var iv = new byte[]
            {
                0x15, 0x8c, 0xad, 0xa6, 0xaf, 0x63, 0x0d, 0x8c,
            };

            // echo -n -e '\xe9\x74\x8e\x5f\xb9\xf3\x99\xce' | openssl enc -e -des-cbc -K E11A5C51A31DD71B -iv 158CADA6AF630D8C -provider legacy | hd
            var expected = new byte[]
            {
                0xdf, 0xb3, 0x0f, 0x80, 0x5c, 0x9b, 0x47, 0xa8, 0x0b, 0x68, 0x6b, 0x47, 0x00, 0xb7, 0x66, 0x20,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CBC_Length17_Pad()
        {
            var input = new byte[]
            {
                0x1a, 0xf1, 0x3a, 0x35, 0x8c, 0xca, 0x3f, 0xd6, 0x2f, 0x65, 0xc1, 0x31, 0x2d, 0x41, 0xe5, 0xc7,
                0xf3,
            };
            var key = new byte[]
            {
                0x74, 0x23, 0x71, 0xed, 0x6d, 0x84, 0x79, 0x61,
            };
            var iv = new byte[]
            {
                0xd0, 0xf8, 0x6f, 0x7f, 0x0c, 0xcc, 0x86, 0x67,
            };

            // echo -n -e '\x1a\xf1\x3a\x35\x8c\xca\x3f\xd6\x2f\x65\xc1\x31\x2d\x41\xe5\xc7\xf3' | openssl enc -e -des-cbc -K 742371ED6D847961 -iv D0F86F7F0CCC8667 -provider legacy | hd
            var expected = new byte[]
            {
                0x11, 0x53, 0x6b, 0x68, 0xe9, 0xb7, 0x08, 0xed, 0x51, 0x23, 0x94, 0xee, 0x3d, 0xac, 0xab, 0xa0,
                0x86, 0x5a, 0x46, 0x6e, 0xe5, 0x5d, 0x4a, 0xe9,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CBC_Length32_NoPad()
        {
            var input = new byte[]
            {
                0x02, 0x45, 0xc8, 0xb8, 0x64, 0x42, 0x17, 0xda, 0x85, 0x21, 0x3e, 0x5c, 0xa6, 0xee, 0xd4, 0xa7,
                0xe6, 0xb3, 0x3b, 0x3f, 0x9c, 0x9e, 0xac, 0x6c, 0xc1, 0xd3, 0xbb, 0xd2, 0xd0, 0x57, 0x22, 0x99,
            };
            var key = new byte[]
            {
                0x3a, 0xc9, 0x2b, 0xfb, 0x1d, 0x0e, 0x8e, 0x31,
            };
            var iv = new byte[]
            {
                0x0c, 0x96, 0x68, 0x4c, 0x46, 0x1d, 0xbb, 0xe1,
            };

            // echo -n -e '\x02\x45\xc8\xb8\x64\x42\x17\xda\x85\x21\x3e\x5c\xa6\xee\xd4\xa7\xe6\xb3\x3b\x3f\x9c\x9e\xac\x6c\xc1\xd3\xbb\xd2\xd0\x57\x22\x99' | openssl enc -e -des-cbc -K 3AC92BFB1D0E8E31 -iv 0C96684C461DBBE1 -provider legacy -nopad | hd
            var expected = new byte[]
            {
                0xfc, 0x48, 0xcb, 0x04, 0x71, 0x03, 0x5a, 0x04, 0xfa, 0x66, 0x1e, 0x12, 0x26, 0x27, 0xf1, 0x98,
                0x19, 0x68, 0xce, 0xea, 0x8e, 0x60, 0x3b, 0xa9, 0xa2, 0x06, 0xbf, 0x18, 0x59, 0xab, 0xd8, 0xd9,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: false).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: false).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CBC_Length32_Pad()
        {
            var input = new byte[]
            {
                0x23, 0xc8, 0x99, 0x59, 0x90, 0x47, 0xcb, 0x63, 0x99, 0x5b, 0xf7, 0x91, 0x87, 0x44, 0x09, 0x2e,
                0xff, 0xa4, 0x21, 0xdc, 0xc3, 0xd9, 0x89, 0xd7, 0x24, 0x0a, 0x32, 0x05, 0x36, 0x60, 0x25, 0xa4,
            };
            var key = new byte[]
            {
                0x17, 0xda, 0xaf, 0x08, 0xbe, 0xc9, 0x08, 0xf3,
            };
            var iv = new byte[]
            {
                0xfe, 0xc7, 0x61, 0xc2, 0x17, 0xfd, 0xaa, 0xc7,
            };

            // echo -n -e '\x23\xc8\x99\x59\x90\x47\xcb\x63\x99\x5b\xf7\x91\x87\x44\x09\x2e\xff\xa4\x21\xdc\xc3\xd9\x89\xd7\x24\x0a\x32\x05\x36\x60\x25\xa4' | openssl enc -e -des-cbc -K 17DAAF08BEC908F3 -iv FEC761C217FDAAC7 -provider legacy | hd
            var expected = new byte[]
            {
                0x93, 0xcb, 0xb1, 0x86, 0x4f, 0xd1, 0x6b, 0x15, 0xc5, 0x00, 0xaf, 0x50, 0xfc, 0xd2, 0x34, 0xdb,
                0x73, 0xa1, 0x6f, 0x4c, 0x9c, 0xcd, 0xd8, 0xf9, 0x95, 0xee, 0xa2, 0xb2, 0x46, 0x1a, 0x5a, 0x9a,
                0xea, 0xb5, 0xb5, 0xb8, 0x97, 0x65, 0xd0, 0x0b,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CBC, pkcs7Padding: true).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CFB_Length8_NoPad()
        {
            var input = new byte[]
            {
                0x8d, 0x3a, 0x4c, 0xa2, 0xfb, 0xde, 0x1e, 0x49,
            };
            var key = new byte[]
            {
                0x3e, 0xc1, 0x34, 0x86, 0x14, 0xc6, 0x2d, 0x39,
            };
            var iv = new byte[]
            {
                0x35, 0x52, 0x79, 0xad, 0x95, 0x01, 0x6f, 0x36,
            };

            // echo -n -e '\x8d\x3a\x4c\xa2\xfb\xde\x1e\x49' | openssl enc -e -des-cfb -K 3EC1348614C62D39 -iv 355279AD95016F36 -provider legacy -nopad | hd
            var expected = new byte[]
            {
                0x9b, 0x67, 0x40, 0x20, 0x40, 0x5e, 0x9e, 0x00,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CFB_Length17_NoPad()
        {
            var input = new byte[]
            {
                0x9b, 0x2e, 0xde, 0xfc, 0x77, 0xc7, 0xc0, 0x27, 0x60, 0x6b, 0x78, 0xfc, 0x13, 0x83, 0xa8, 0x38,
                0xbb,
            };
            var key = new byte[]
            {
                0x65, 0xca, 0xfd, 0x94, 0x82, 0xde, 0x38, 0x99,
            };
            var iv = new byte[]
            {
                0x28, 0x8c, 0xc4, 0x84, 0xfd, 0x32, 0x8c, 0xca,
            };

            // echo -n -e '\x9b\x2e\xde\xfc\x77\xc7\xc0\x27\x60\x6b\x78\xfc\x13\x83\xa8\x38\xbb' | openssl enc -e -des-cfb -K 65CAFD9482DE3899 -iv 288CC484FD328CCA -provider legacy -nopad | hd
            var expected = new byte[]
            {
                0x03, 0x86, 0xd9, 0x49, 0x1b, 0x60, 0x76, 0xec, 0x06, 0x47, 0xd3, 0xe0, 0xfd, 0x33, 0x08, 0xc4,
                0x3f,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }

        [TestMethod]
        public void DES_CFB_Length32_NoPad()
        {
            var input = new byte[]
            {
                0x16, 0x06, 0xcc, 0x00, 0x22, 0xd2, 0x76, 0x00, 0x0d, 0x25, 0xa9, 0x4e, 0x31, 0x25, 0xb1, 0xaa,
                0x40, 0xf1, 0x2f, 0x36, 0x72, 0xa2, 0x18, 0x4f, 0xa6, 0x62, 0x4f, 0x3b, 0xfb, 0xa3, 0x63, 0x38,
            };
            var key = new byte[]
            {
                0xec, 0x32, 0xfd, 0x7d, 0xdb, 0x38, 0x99, 0x93,
            };
            var iv = new byte[]
            {
                0x53, 0xfc, 0x86, 0x5d, 0x35, 0xe9, 0x68, 0x02,
            };

            // echo -n -e '\x16\x06\xcc\x00\x22\xd2\x76\x00\x0d\x25\xa9\x4e\x31\x25\xb1\xaa\x40\xf1\x2f\x36\x72\xa2\x18\x4f\xa6\x62\x4f\x3b\xfb\xa3\x63\x38' | openssl enc -e -des-cfb -K EC32FD7DDB389993 -iv 53FC865D35E96802 -provider legacy -nopad | hd
            var expected = new byte[]
            {
                0x73, 0x97, 0xc2, 0xcb, 0x6b, 0xec, 0xa5, 0x00, 0x5d, 0xaf, 0x5c, 0xf3, 0x10, 0x55, 0x5e, 0xe6,
                0x6e, 0x97, 0x4e, 0xd3, 0xad, 0x27, 0x33, 0xe4, 0xa0, 0x8e, 0x35, 0xc9, 0x1a, 0x17, 0x07, 0x64,
            };

            var actual = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Encrypt(input);

            CollectionAssert.AreEqual(expected, actual);

            var decrypted = new DesCipher(key, (byte[])iv.Clone(), BlockCipherMode.CFB, pkcs7Padding: false).Decrypt(actual);

            CollectionAssert.AreEqual(input, decrypted);
        }
    }
}
