<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="coverlet.msbuild" Version="10.0.1" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="3.0.5" />
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.125" />
    <!-- Should stay on LTS .NET releases. -->
    <PackageVersion Include="Microsoft.Bcl.Cryptography" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageVersion Include="MSTest" Version="4.3.3" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.10.91" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <!-- Should stay on LTS .NET releases. -->
    <PackageVersion Include="System.Formats.Asn1" Version="10.0.10" />
    <PackageVersion Include="Testcontainers" Version="4.13.0" />
  </ItemGroup>
</Project>